dist: xenial

services:
  - docker

language: minimal

env:
  DOCKSAL_VERSION: develop

install:
  # Install Docksal to have a matching versions of Docker on the build host
  - curl -fsSL https://get.docksal.io | bash
  - fin version
  - fin sysinfo

before_script:
  - git clone https://github.com/docksal/drupal8.git ../drupal8
  - cd ../drupal8
  - fin start
  - git clone https://github.com/docksal/drupal7.git ../drupal7
  - cd ../drupal7
  - fin start
  - fin pl -a
  - cd ${TRAVIS_BUILD_DIR}

script:
  - make
  - make test

after_success:
  - make release

after_failure:
  - make logs
