dist: xenial

language: minimal

services:
  - docker

env:
  DOCKSAL_VERSION: develop

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libfcgi0ldbl  # cgi-fcgi binary used in tests

install:
  - git clone https://github.com/docksal/bats.git tests/scripts/bats
  - cd tests/scripts/bats
  - sudo ./install.sh /usr/local
  # Install Docksal to have a matching versions of Docker on the build host
  - curl -fsSL https://get.docksal.io | bash
  - fin version
  - fin sysinfo

before_script:
  - git clone https://github.com/docksal/drupal8.git ../drupal8
  - cd ../drupal8
  - fin start
  - git clone https://github.com/docksal/drupal7.git ../drupal7
  - cd ../drupal7
  - fin start
  - fin pl -a
  - cd ${TRAVIS_BUILD_DIR}

script:
  - make
  - make test

after_success:
  - make release

after_failure:
  - make logs
